{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 01:53:16,791+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 02:55:05,038+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-10-22 02:55:10,162+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/symbol-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFC07C350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))","timestamp":"2025-10-22 05:53:07,329+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 428, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 99, in read\n    if not read_callback():\n           ^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 442, in read\n    raise e\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 437, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_core.py\", line 406, in recv_data_frame\n    frame = self.recv_frame()\n            ^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_core.py\", line 445, in recv_frame\n    return self.frame_buffer.recv_frame()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_abnf.py\", line 338, in recv_frame\n    self.recv_header()\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_abnf.py\", line 294, in recv_header\n    header = self.recv_strict(2)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_abnf.py\", line 373, in recv_strict\n    bytes_ = self.recv(min(16384, shortage))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_core.py\", line 529, in _recv\n    return recv(self.sock, bufsize)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_socket.py\", line 122, in recv\n    raise WebSocketConnectionClosedException(\nwebsocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\util\\connection.py\", line 72, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 963, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 716, in urlopen\n    httplib_response = self._make_request(\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 404, in _make_request\n    self._validate_conn(conn)\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 1061, in _validate_conn\n    conn.connect()\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 363, in connect\n    self.sock = conn = self._new_conn()\n                       ^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CEFC07C350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 802, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 594, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/symbol-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFC07C350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 63, in symbol_to_hsmtoken\n    response = requests.post(\n               ^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/symbol-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CEFC07C350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))","exception_name":"ConnectionError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-10-22 05:53:07,401+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-10-22 05:53:07,838+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 428, in setSock\n    dispatcher.read(self.sock.sock, read, check)\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 99, in read\n    if not read_callback():\n           ^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 442, in read\n    raise e\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_app.py\", line 437, in read\n    op_code, frame = self.sock.recv_data_frame(True)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_core.py\", line 406, in recv_data_frame\n    frame = self.recv_frame()\n            ^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_core.py\", line 445, in recv_frame\n    return self.frame_buffer.recv_frame()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_abnf.py\", line 338, in recv_frame\n    self.recv_header()\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_abnf.py\", line 294, in recv_header\n    header = self.recv_strict(2)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_abnf.py\", line 373, in recv_strict\n    bytes_ = self.recv(min(16384, shortage))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_core.py\", line 529, in _recv\n    return recv(self.sock, bufsize)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\websocket\\_socket.py\", line 122, in recv\n    raise WebSocketConnectionClosedException(\nwebsocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"E:\\paper\\paper\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-10-22 05:54:03,966+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 10:32:21,412+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1334] data_ws","message":{"code":-300,"message":"Please provide valid token","s":"error","type":"sub"},"timestamp":"2025-10-22 10:32:29,878+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 10:36:17,995+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:02:31,526+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:13:38,980+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:13:51,332+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:14:05,090+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:20:04,201+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:30:35,631+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:30:51,220+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:43:27,474+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:43:56,812+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:52:25,663+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 11:56:05,704+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:16:35,437+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:16:45,144+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:32:12,561+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:38:12,529+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:50:08,788+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:52:52,706+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:55:17,932+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:55:31,873+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:55:43,784+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:56:08,835+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:56:31,188+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:56:44,785+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:57:46,332+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:58:08,096+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 12:58:51,844+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-10-22 13:20:56,972+0530","service":"FyersDataSocket"}
